name: Pipeline Trigger Request
description: Provide details to trigger the pipeline
title: "[Trigger]: "
labels: ["pipeline"]
body:
  - type: input
    id: service_name
    attributes:
      label: Service Name
      placeholder: example-service
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: dev / qa / prod
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v1.0.0
    validations:
      required: true