name: Pipeline Trigger Request
description: Provide details to trigger the pipeline
title: "[Trigger]: "
labels: ["pipeline"]
body:
  - type: dropdown
    id: agent_name
    attributes:
      label: Agent Name
      description: Select the agent to use
      options:
        - db2
        - operationsagent
        - cics
        - cics-pd-agent
        - ims
        - ims-mcp-agent
        - upgradeagent
        - upgradeagent-zosmf-v2
        - tls-agent
        - aiopsagent
        - automation-insights
        - workload-scheduler-agent
    validations:
      required: true

  - type: input
    id: image
    attributes:
      label: Image
      description: Specify the container image to use
      placeholder: e.g., icr.io/wxa4z-agentic-development/upgrade-agent:granite-4-8b
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: Model decides the namespace in deployment
      placeholder: e.g., ibm/granite-3-3-8b-instruct
    validations:
      required: true

  - type: dropdown
    id: test_type
    attributes:
      label: Test Type
      description: Select the test type
      options:
        - direct
        - wxo
    validations:
      required: true

  - type: dropdown
    id: tool_call_eval
    attributes:
      label: Tool Call Evaluation
      description: Enable or disable tool call evaluation
      options:
        - "true"
        - "false"
    validations:
      required: true

# Made with Bob
